### ISSUE TITLE
Unable to run the testSimpleFMU.py

### ISSUE THREAD

**Issue by gitting-around** [ERIGrid/ns3-fmi-export#1]
Hi,

I am trying to run the testSimpleFMU.py script in Ubuntu 18.04, with Python 3.6.9. I get the following errors:

`ModuleNotFoundError: No module named 'urlparse'
`

Now I am able to circumvent this by doing: 
`import urllib`
`from urllib.parse import urlparse`
`from urllib.parse import urljoin`
`from urllib import request`
in both extractFMU.py and FMUCosimulatioV1.py, and changing the calls within `scripts.`

After I have marked the SimpleFMU.so as executable and rezipped into an fmu, I get

`AttributeError: 'FMUCoSimulationV1' object has no attribute 'fmi_component'`

so then I add `self.fmi_component = None` in the `__init__` of FMUCosimulatioV1.py.

At that point it starts complaining about:

```bash
/home/blah/Desktop/ns3/ns-3-allinone/ns-3.30/src/fmu-examples/examples/../SimpleFMU.fmu is not a valid ZIP archive
Traceback (most recent call last):
  File "test/testSimpleFMU.py", line 30, in <module>
    logging_on = logging_on
  File "/home/blah/Desktop/ns3/ns-3-allinone/ns-3.30/src/fmu-examples/examples/test/FMUCoSimulationV1.py", line 273, in instantiateSlave
    c_char_p( name ),
TypeError: bytes or integer address expected instead of str instance

```
 by turning `c_char_p` into `c_wchar_p` below (FMUCosimulatioV1.py, lines 273-276)

```python
c_char_p( name ),
c_char_p( fmu_guid ),
c_char_p( fmu_uri ),
c_char_p( fmu_mime_type ),
```

and converting to int the expression within brackets in (FMUCosimulatioV1.py, lines 278-279) 

```python
c_char( self.fmi_true if visible is True else self.fmi_false ),
c_char( self.fmi_true if interactive is True else self.fmi_false ),
```

I am stuck at the following error at line 281 `c_char( self.fmi_true if logging_on is True else self.fmi_false )`, where the same trick as above didn't cut it:

```bash
ZIP archive
Traceback (most recent call last):
  File "test/testSimpleFMU.py", line 30, in <module>
    logging_on = logging_on
  File "/home/blah/Desktop/ns3/ns-3-allinone/ns-3.30/src/fmu-examples/examples/test/FMUCoSimulationV1.py", line 281, in instantiateSlave
    c_char( self.fmi_true if logging_on is True else self.fmi_false )
TypeError: one character bytes, bytearray or integer expected
```

Any insights?

**Comment by ewidl** [comment]
The error about `FMUCoSimulationV1` having no attribute called `fmi_component` looks suspicious. This attribute is initialized when calling method `instantiateSlave`, which should be the first method to be called on the object (compare with FMI standard).

I will take a look at this in the coming days ...

**Comment by gitting-around** [comment]
Hi, any news on this?

Some more details on how I set up the environment:

I run `./waf configure --with-fmi-export=/home/.../fmipp`, which gives the following output:

```bash
Setting top to                           : /home/.../ns3/ns-3-allinone/ns-3.30 
Setting out to                           : /home/.../ns3/ns-3-allinone/ns-3.30/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking for cc version                  : 7.5.0 
Checking for 'g++' (C++ compiler)        : /usr/bin/g++ 
Checking for compilation flag -Wl,--soname=foo support : ok 
Checking for compilation flag -std=c++11 support       : ok 
Checking boost includes                                : 1_65_1 
Checking boost libs                                    : ok 
Checking for boost linkage                             : ok 
Checking for program 'python'                          : /usr/bin/python3 
Checking for python version >= 2.3                     : 3.6.9 
python-config                                          : /usr/bin/python3-config 
Asking python-config for pyembed '--cflags --libs --ldflags --embed' flags : not found 
Asking python-config for pyembed '--cflags --libs --ldflags' flags         : yes 
Testing pyembed configuration                                              : yes 
Asking python-config for pyext '--cflags --libs --ldflags' flags           : yes 
Testing pyext configuration                                                : yes 
Checking for compilation flag -fvisibility=hidden support                  : ok 
Checking for compilation flag -Wno-array-bounds support                    : ok 
Checking for pybindgen location                                            : ../pybindgen (guessed) 
Checking for python module 'pybindgen'                                     : 0.20.0 
Checking for pybindgen version                                             : 0.20.0 
Checking for code snippet                                                  : yes 
Checking for types uint64_t and unsigned long equivalence                  : no 
Checking for code snippet                                                  : no 
Checking for types uint64_t and unsigned long long equivalence             : yes 
Checking for the apidefs that can be used for Python bindings              : gcc-LP64 
Checking for internal GCC cxxabi                                           : complete 
Checking for python module 'pygccxml'                                      : not found 
Checking for click location                                                : not found 
Checking for program 'pkg-config'                                          : /usr/bin/pkg-config 
Checking for 'gtk+-3.0'                                                    : yes 
Checking for 'libxml-2.0'                                                  : yes 
checking for uint128_t                                                     : not found 
checking for __uint128_t                                                   : yes 
Checking high precision implementation                                     : 128-bit integer (default) 
Checking for header stdint.h                                               : yes 
Checking for header inttypes.h                                             : yes 
Checking for header sys/inttypes.h                                         : not found 
Checking for header sys/types.h                                            : yes 
Checking for header sys/stat.h                                             : yes 
Checking for header dirent.h                                               : yes 
Checking for header stdlib.h                                               : yes 
Checking for header signal.h                                               : yes 
Checking for header pthread.h                                              : yes 
Checking for header stdint.h                                               : yes 
Checking for header inttypes.h                                             : yes 
Checking for header sys/inttypes.h                                         : not found 
Checking for library rt                                                    : yes 
Checking for header sys/ioctl.h                                            : yes 
Checking for header net/if.h                                               : yes 
Checking for header net/ethernet.h                                         : yes 
Checking for header linux/if_tun.h                                         : yes 
Checking for header netpacket/packet.h                                     : yes 
Checking for FMI++ location                                                : /home/.../ns3/fmipp (given) 
Checking for FMI++ library path                                            : /home/.../ns3/ns-3-allinone/ns-3.30/src/fmi-export/lib 
Checking for C compiler                                                    : /usr/bin/gcc 
Checking for C++ compiler                                                  : /usr/bin/g++ 
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   date_time
--   system
--   filesystem
-- Configuring done
-- Generating done
-- Build files have been written to: /home/.../ns3/ns-3-allinone/ns-3.30/src/fmi-export/lib
[ 37%] Built target fmi2
[ 65%] Built target fmipp_backend
[100%] Built target fmipp_frontend
Checking for NSC location                                                  : not found 
Checking for OpenFlow location                                             : not found 
Checking for 'sqlite3'                                                     : yes 
Checking for header linux/if_tun.h                                         : yes 
Checking for python module 'gi'                                            : 3.26.1 
Checking for python module 'gi.repository.GObject'                         : ok 
Checking for python module 'cairo'                                         : ok 
Checking for python module 'pygraphviz'                                    : 1.4rc1 
Checking for python module 'gi.repository.Gtk'                             : ok 
Checking for python module 'gi.repository.Gdk'                             : ok 
Checking for python module 'gi.repository.Pango'                           : ok 
Checking for python module 'gi.repository.GooCanvas'                       : ok 
Checking for program 'sudo'                                                : /usr/bin/sudo 
Checking for program 'valgrind'                                            : /usr/bin/valgrind 
Checking for 'gsl'                                                         : not found 
libgcrypt-config                                                           : not found 
Checking for compilation flag -fstrict-aliasing support                    : ok 
Checking for compilation flag -fstrict-aliasing support                    : ok 
Checking for compilation flag -Wstrict-aliasing support                    : ok 
Checking for compilation flag -Wstrict-aliasing support                    : ok 
Checking for program 'doxygen'                                             : not found 
---- Summary of optional NS-3 features:
Build profile                 : debug
Build directory               : 
BRITE Integration             : not enabled (BRITE not enabled (see option --with-brite))
DES Metrics event collection  : not enabled (defaults to disabled)
Emulation FdNetDevice         : enabled
Examples                      : not enabled (defaults to disabled)
File descriptor NetDevice     : enabled
GNU Scientific Library (GSL)  : not enabled (GSL not found)
Gcrypt library                : not enabled (libgcrypt not found: you can use libgcrypt-config to find its location.)
GtkConfigStore                : enabled
MPI Support                   : not enabled (option --enable-mpi not selected)
NS-3 Click Integration        : not enabled (nsclick not enabled (see option --with-nsclick))
NS-3 FMU Export Examples      : enabled
NS-3 FMU Export Utility       : enabled
NS-3 OpenFlow Integration     : not enabled (OpenFlow not enabled (see option --with-openflow))
Network Simulation Cradle     : not enabled (NSC not found (see option --with-nsc))
PlanetLab FdNetDevice         : not enabled (PlanetLab operating system not detected (see option --force-planetlab))
PyViz visualizer              : enabled
Python API Scanning Support   : not enabled (Missing 'pygccxml' Python module)
Python Bindings               : enabled
Real Time Simulator           : enabled
SQlite stats data output      : enabled
Tap Bridge                    : enabled
Tap FdNetDevice               : enabled
Tests                         : not enabled (defaults to disabled)
Threading Primitives          : enabled
Use sudo to set suid bit      : not enabled (option --enable-sudo not selected)
XmlIo                         : enabled
'configure' finished successfully (3.940s)
```

and then `./waf` which gives:

```bash
Waf: Entering directory `/home/.../ns3/ns-3-allinone/ns-3.30/build'
[2010/2074] Linking build/utils/ns3-dev-test-runner-debug
Waf: Leaving directory `/home/.../ns3/ns-3-allinone/ns-3.30/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (2.058s)

Modules built:
antenna                   aodv                      applications              
bridge                    buildings                 config-store              
core                      csma                      csma-layout               
dsdv                      dsr                       energy                    
fd-net-device             flow-monitor              fmi-export (no Python)    
fmu-examples (no Python)  internet                  internet-apps             
lr-wpan                   lte                       mesh                      
mobility                  mpi                       netanim (no Python)       
network                   nix-vector-routing        olsr                      
point-to-point            point-to-point-layout     propagation               
sixlowpan                 spectrum                  stats                     
tap-bridge                test (no Python)          topology-read             
traffic-control           uan                       virtual-net-device        
visualizer                wave                      wifi                      
wimax                     

Modules not built (see ns-3 tutorial for explanation):
brite                     click                     openflow       
```

**Comment by ewidl** [comment]
A short questions to better understand your ns-3 setup: How did you install ns-3? Did you use the `ns-3-dev` branch or the `ns-3-allinone` framework?

**Comment by gitting-around** [comment]
I followed [https://www.nsnam.org/wiki/Installation#Downloading_ns-3_Using_Git](this). So the ns-3-allinone. I can try to install it again and provide the output in the terminal, maybe there is a clue there?

**Comment by omarchakroun** [comment]
Technically if you got that error related to the urlparse, you can solve it just by using python2 when you are trying to launch the testSimpleFMU.py script. i got the same error because by default my environment points to python3. i was able to make it run by typing python2 ./testSimpleFMU.py

**Comment by ewidl** [comment]
Short update:

The problems you experience are caused by the fact that the FMI export module was developed for an older version of ns-3 (ns-3.29), which still used Python 2. I am currently working on fixing this, and I am confident that I will finish this quite soon. However, I also added a [new branch](https://github.com/ERIGrid/ns3-fmi-export/tree/ns-3.29) with specific installation instructions for ns-3.29, which was the version this package was developed for ...

**Comment by ewidl** [comment]
Commit 122190b updates this package to work with ns-3.33 (currently the latest ns-3-dev release).

The main issue was the switch from Python 2 to Python 3, where the latter distinguishes between bytes and string. Package *ctypes*, which is used to load the FMU shared library, expects bytes as inputs to `c_char_p` function arguments, not strings. The solution was to use `.encode('utf-8')` to convert the strings to bytes ...

**Comment by gitting-around** [comment]
I tried the branch for ns-3.29, and the fix works, I am now able to run the script. Thanks!
